// cms-microapp-vue/src/App.vue
<template>
  <div id="app">
    <img alt="Vue logo" src="./assets/logo.png" />
    <HelloWorld msg="CloudBase CMS 微应用" />
    <button @click="callFunction">
      调用云函数
    </button>
    <p>调用结果：{{ result }}</p>
  </div>
</template>

<script>
import HelloWorld from './components/HelloWorld.vue'

export default {
  name: 'App',
  components: {
    HelloWorld,
  },
  data() {
    return { result: '' }
  },
  methods: {
    callFunction() {
      window.cloudbase
        .callFunction({
          name: 'tcb-ext-cms-service',
          data: {
            options: { sort: {}, filter: {}, pageSize: 10, fuzzyFilter: {}, page: 1 },
            resource: 'fsd',
            action: 'getMany',
          },
        })
        .then((ret) => (this.result = JSON.stringify(ret)))
        .catch((ret) => (this.result = JSON.stringify(ret)))
    },
  },
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

// cms-microapp-react/src/App.tsx
import React, { useState } from 'react'
import { HashRouter, Link, Route, Switch } from 'react-router-dom'
import About from './About'
import logo from './logo.svg'
import './App.css'

const microAppID = 'reactApp'

function App() {
  const [result, setResult] = useState('')

  // 调用云函数
  const callFunction = () => {
    window.cloudbase
      .callFunction({
        name: 'tcb-ext-cms-service',
        data: {
          options: { sort: {}, filter: {}, pageSize: 10, fuzzyFilter: {}, page: 1 },
          resource: 'fsd',
          action: 'getMany'
        }
      })
      .then((ret: any) => setResult(JSON.stringify(ret)))
      .catch((ret: any) => setResult(JSON.stringify(ret)))
  }

  return (
    <HashRouter basename={`/project/microapp/${microAppID}/`}>
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <p>CloudBase CMS 微应用</p>
          <div>
            <Link to="/" className="App-link">
              Home
            </Link>
            &nbsp;|&nbsp;
            <Link to="/about" className="App-link">
              About
            </Link>
          </div>
          <p>
            <button onClick={() => callFunction()}>调用云函数</button>
            <p>调用结果：{result}</p>
          </p>
        </header>
        <Switch>
          <Route exact path="/">
            <h2 style={{ color: '#fff' }}>Home Page</h2>
          </Route>
          <Route path="/about">
            <About />
          </Route>
        </Switch>
      </div>
    </HashRouter>
  )
}

export default App
